### ISSUE TITLE
aardvark-dns should be in /usr/libexec/podman

### ISSUE THREAD

**Issue by flukeeey** [chimera-linux/cports#1330]
The current `aardvark-dns` package installs the aardvark-dns binary to /usr/bin, which podman apparently does not check. On a fresh install, with the netavark network backend set in containers.conf, `podman info` lists:

```
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: Unknown
    package: netavark-1.10.1-r0
    path: /usr/libexec/podman/netavark
    version: netavark 1.10.1

```
Creating a /usr/libexec/podman/aardvark-dns symlink that points to /usr/bin/aardvark-dns fixes the problem and `podman info` now shows:

```
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: /usr/libexec/podman/aardvark-dns symlink target is owned by aardvark-dns-1.10.0-r0
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.10.0
    package: netavark-1.10.1-r0
    path: /usr/libexec/podman/netavark
    version: netavark 1.10.1
```

Container DNS will now work as expected.

I can submit a package fix PR if you like @q66 ?
